spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/books
        username: root
        password: Anthrax@22.
    
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true
    application:
        name: ORDER-SERVICE
    
server:
    port: 8080

eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: "http://localhost:8761/eureka"
        instance:
            hostname: localhost